### ISSUE TITLE
<|endoftext|> is a disallowed special token

### ISSUE THREAD

**Issue by RedwindA** [BedirT/LLM-Token-Counter-VSCode#1]
![image](https://github.com/BedirT/GPT-Token-Counter-VSCode/assets/128586631/c820ac09-4b24-42e0-a71e-db3f6c41d47e)

**Comment by BedirT** [comment]
Hey!

I am not able to reproduce this, can you provide more information?

**Comment by RedwindA** [comment]
I'm sorry, I can't reproduce this issue now and I have forgotten how I triggered it at that time😭

**Comment by BedirT** [comment]
Lol, that's fine, it might be resolved from the tokenizer itself.

**Comment by RedwindA** [comment]
I triggered the issue again, reproduced by 
1. creating a new blank text file 
2. pasting the text containing the special token '<|im_start|>'
3. switching the model in the plugin (e.g. from gpt-4 to gpt-3.5)

![image](https://github.com/BedirT/LLM-Token-Counter-VSCode/assets/128586631/ddfb19c4-a984-4128-bc1d-5b5839581f2f)

**Comment by BedirT** [comment]
Got it! Was able to reproduce I will look into it thanks

**Comment by BedirT** [comment]
Quick update on this; I have finished the fix, but yet to test it more, I will have some time this weekend to finalize the push.
