### ISSUE TITLE
"Hung" Counter stops responding

### ISSUE THREAD

**Issue by LupoGrigi0** [BedirT/LLM-Token-Counter-VSCode#2]
i'm working on a very large JSON file, 
the token counter froze at 10455 and will no longer respond
<img width="278" alt="image" src="https://github.com/BedirT/LLM-Token-Counter-VSCode/assets/136217188/9ce96848-a299-47f0-a8e4-5a2fa05035ec">

**Comment by BedirT** [comment]
Can you give me a little more detail on your system and maybe the size of the file? In my system I am able to get up to 2 million tokens instantly calculated. If the file is very large it might take some time since the calculations depend on openai's `tiktoken` library.
